### ISSUE TITLE
Priority: Prototype only

### ISSUE THREAD

**Issue by ghost** [anchorboat/mockups#1]
Avoid fancy stuff if you can. We probably gonna use a heavy lof of bootstrap, jquery, sass, coffeescript, js.

Note that, the layout template is not 100% compatible with pure static pages technologies. So you maybe had to learn the MVC template toolkit too, to integrate your front end code and design into the website.

Anyway, good work. :+1:

**Comment by elevenpassin** [comment]
I'm just implementing design as I go.

**Comment by ghost** [comment]
A reference for the master site, I see.
